# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skjerm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(800, 480)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setMaximumSize(QtCore.QSize(800, 480))
        self.gridFrame_7 = QtWidgets.QFrame(Form)
        self.gridFrame_7.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.gridFrame_7.setMinimumSize(QtCore.QSize(800, 480))
        self.gridFrame_7.setMaximumSize(QtCore.QSize(800, 480))
        self.gridFrame_7.setObjectName("gridFrame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridFrame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_104 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_104.setObjectName("label_104")
        self.gridLayout_16.addWidget(self.label_104, 1, 1, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_99.setObjectName("label_99")
        self.gridLayout_16.addWidget(self.label_99, 0, 1, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_101.setObjectName("label_101")
        self.gridLayout_16.addWidget(self.label_101, 1, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_100.setObjectName("label_100")
        self.gridLayout_16.addWidget(self.label_100, 0, 0, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_107.setObjectName("label_107")
        self.gridLayout_16.addWidget(self.label_107, 2, 2, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_106.setObjectName("label_106")
        self.gridLayout_16.addWidget(self.label_106, 2, 1, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_103.setObjectName("label_103")
        self.gridLayout_16.addWidget(self.label_103, 0, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_102.setObjectName("label_102")
        self.gridLayout_16.addWidget(self.label_102, 2, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_105.setObjectName("label_105")
        self.gridLayout_16.addWidget(self.label_105, 1, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_16, 0, 2, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_63 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_63.setObjectName("label_63")
        self.gridLayout_11.addWidget(self.label_63, 0, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_64.setObjectName("label_64")
        self.gridLayout_11.addWidget(self.label_64, 0, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_65.setObjectName("label_65")
        self.gridLayout_11.addWidget(self.label_65, 1, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_66.setObjectName("label_66")
        self.gridLayout_11.addWidget(self.label_66, 2, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_67.setObjectName("label_67")
        self.gridLayout_11.addWidget(self.label_67, 0, 2, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_68.setObjectName("label_68")
        self.gridLayout_11.addWidget(self.label_68, 1, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_69.setObjectName("label_69")
        self.gridLayout_11.addWidget(self.label_69, 1, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_70.setObjectName("label_70")
        self.gridLayout_11.addWidget(self.label_70, 2, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_71.setObjectName("label_71")
        self.gridLayout_11.addWidget(self.label_71, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_11, 2, 3, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 3, 1, 1, 1)
        self.Label_20 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_20.setObjectName("Label_20")
        self.gridLayout_4.addWidget(self.Label_20, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 4, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.Label_18 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_18.setObjectName("Label_18")
        self.gridLayout_2.addWidget(self.Label_18, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.Label_19 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_19.setObjectName("Label_19")
        self.gridLayout_3.addWidget(self.Label_19, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_51 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 1, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 2, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 3, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 3, 1, 1, 1)
        self.Label_22 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_22.setObjectName("Label_22")
        self.gridLayout_6.addWidget(self.Label_22, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 3, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 2, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Test1 = QtWidgets.QPushButton(self.gridFrame_7)
        self.Test1.setObjectName("Test1")
        self.verticalLayout.addWidget(self.Test1)
        self.Test2 = QtWidgets.QPushButton(self.gridFrame_7)
        self.Test2.setObjectName("Test2")
        self.verticalLayout.addWidget(self.Test2)
        self.Test3 = QtWidgets.QPushButton(self.gridFrame_7)
        self.Test3.setObjectName("Test3")
        self.verticalLayout.addWidget(self.Test3)
        self.label_117 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_117.setObjectName("label_117")
        self.verticalLayout.addWidget(self.label_117)
        self.gridLayout_7.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_10 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_38.setObjectName("label_38")
        self.gridLayout_10.addWidget(self.label_38, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_10, 2, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_41 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 3, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 3, 1, 1, 1)
        self.Label_21 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_21.setObjectName("Label_21")
        self.gridLayout_5.addWidget(self.Label_21, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 1, 4, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(self.gridFrame_7)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_9, 2, 1, 1, 1)
        self.gridLayout_0 = QtWidgets.QGridLayout()
        self.gridLayout_0.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_0.setContentsMargins(8, 0, 0, -1)
        self.gridLayout_0.setSpacing(6)
        self.gridLayout_0.setObjectName("gridLayout_0")
        self.label_04 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_04.setObjectName("label_04")
        self.gridLayout_0.addWidget(self.label_04, 1, 2, 1, 1)
        self.label_05 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_05.setObjectName("label_05")
        self.gridLayout_0.addWidget(self.label_05, 2, 2, 1, 1)
        self.label_01 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_01.setObjectName("label_01")
        self.gridLayout_0.addWidget(self.label_01, 1, 0, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_03.setObjectName("label_03")
        self.gridLayout_0.addWidget(self.label_03, 3, 0, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_07.setObjectName("label_07")
        self.gridLayout_0.addWidget(self.label_07, 3, 1, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_02.setObjectName("label_02")
        self.gridLayout_0.addWidget(self.label_02, 2, 0, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_06.setObjectName("label_06")
        self.gridLayout_0.addWidget(self.label_06, 3, 2, 1, 1)
        self.Label_08 = QtWidgets.QLabel(self.gridFrame_7)
        self.Label_08.setObjectName("Label_08")
        self.gridLayout_0.addWidget(self.Label_08, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_0, 0, 0, 1, 1)
        self.gridFrame_8 = QtWidgets.QFrame(Form)
        self.gridFrame_8.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.gridFrame_8.setMinimumSize(QtCore.QSize(800, 480))
        self.gridFrame_8.setMaximumSize(QtCore.QSize(800, 480))
        self.gridFrame_8.setObjectName("gridFrame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridFrame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.square_11 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_11.setObjectName("square_11")
        self.gridLayout_8.addWidget(self.square_11, 2, 3, 1, 1)
        self.square_6 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_6.setObjectName("square_6")
        self.gridLayout_8.addWidget(self.square_6, 0, 2, 1, 1)
        self.square_1 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_1.setObjectName("square_1")
        self.gridLayout_8.addWidget(self.square_1, 1, 0, 1, 1)
        self.square_10 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_10.setObjectName("square_10")
        self.gridLayout_8.addWidget(self.square_10, 1, 3, 1, 1)
        self.square_2 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_2.setObjectName("square_2")
        self.gridLayout_8.addWidget(self.square_2, 2, 0, 1, 1)
        self.square_7 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_7.setObjectName("square_7")
        self.gridLayout_8.addWidget(self.square_7, 1, 2, 1, 1)
        self.square_3 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_3.setObjectName("square_3")
        self.gridLayout_8.addWidget(self.square_3, 0, 1, 1, 1)
        self.square_8 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_8.setObjectName("square_8")
        self.gridLayout_8.addWidget(self.square_8, 2, 2, 1, 1)
        self.square_5 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_5.setObjectName("square_5")
        self.gridLayout_8.addWidget(self.square_5, 2, 1, 1, 1)
        self.square_14 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_14.setObjectName("square_14")
        self.gridLayout_8.addWidget(self.square_14, 2, 4, 1, 1)
        self.square_9 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_9.setObjectName("square_9")
        self.gridLayout_8.addWidget(self.square_9, 0, 3, 1, 1)
        self.square_12 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_12.setObjectName("square_12")
        self.gridLayout_8.addWidget(self.square_12, 0, 4, 1, 1)
        self.square_0 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_0.setObjectName("square_0")
        self.gridLayout_8.addWidget(self.square_0, 0, 0, 1, 1)
        self.square_13 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_13.setObjectName("square_13")
        self.gridLayout_8.addWidget(self.square_13, 1, 4, 1, 1)
        self.square_4 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_4.setObjectName("square_4")
        self.gridLayout_8.addWidget(self.square_4, 1, 1, 1, 1)
        self.square_9.raise_()
        self.square_8.raise_()
        self.square_7.raise_()
        self.square_6.raise_()
        self.square_5.raise_()
        self.square_4.raise_()
        self.square_3.raise_()
        self.square_2.raise_()
        self.square_14.raise_()
        self.square_13.raise_()
        self.square_12.raise_()
        self.square_11.raise_()
        self.square_10.raise_()
        self.square_1.raise_()
        self.square_0.raise_()
        self.gridFrame_8.raise_()
        self.gridFrame_7.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_104.setText(_translate("Form", "TextLabel"))
        self.label_99.setText(_translate("Form", "TextLabel"))
        self.label_101.setText(_translate("Form", "TextLabel"))
        self.label_100.setText(_translate("Form", "TextLabel"))
        self.label_107.setText(_translate("Form", "TextLabel"))
        self.label_106.setText(_translate("Form", "TextLabel"))
        self.label_103.setText(_translate("Form", "TextLabel"))
        self.label_102.setText(_translate("Form", "TextLabel"))
        self.label_105.setText(_translate("Form", "TextLabel"))
        self.label_63.setText(_translate("Form", "TextLabel"))
        self.label_64.setText(_translate("Form", "TextLabel"))
        self.label_65.setText(_translate("Form", "TextLabel"))
        self.label_66.setText(_translate("Form", "TextLabel"))
        self.label_67.setText(_translate("Form", "TextLabel"))
        self.label_68.setText(_translate("Form", "TextLabel"))
        self.label_69.setText(_translate("Form", "TextLabel"))
        self.label_70.setText(_translate("Form", "TextLabel"))
        self.label_71.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "Label_31"))
        self.label_34.setText(_translate("Form", "Label_34"))
        self.label_32.setText(_translate("Form", "Label_32"))
        self.label_35.setText(_translate("Form", "Label_35"))
        self.label_36.setText(_translate("Form", "Label_36"))
        self.label_33.setText(_translate("Form", "Labe_33"))
        self.label_37.setText(_translate("Form", "Label_37"))
        self.Label_20.setText(_translate("Form", "R1"))
        self.label_15.setText(_translate("Form", "Label_15"))
        self.label_11.setText(_translate("Form", "Label_11"))
        self.label_16.setText(_translate("Form", "Label_16"))
        self.label_12.setText(_translate("Form", "Label_12"))
        self.label_13.setText(_translate("Form", "Labe_13"))
        self.label_14.setText(_translate("Form", "Label_14"))
        self.Label_18.setText(_translate("Form", "L2"))
        self.label_17.setText(_translate("Form", "Label_17"))
        self.label_24.setText(_translate("Form", "Label_24"))
        self.label_21.setText(_translate("Form", "Label_21"))
        self.label_26.setText(_translate("Form", "Label_26"))
        self.label_25.setText(_translate("Form", "Label_25"))
        self.label_27.setText(_translate("Form", "Label_27"))
        self.label_22.setText(_translate("Form", "Label_22"))
        self.label_23.setText(_translate("Form", "Labe_23"))
        self.Label_19.setText(_translate("Form", "L3"))
        self.label_51.setText(_translate("Form", "Label_51"))
        self.label_54.setText(_translate("Form", "Label_54"))
        self.label_52.setText(_translate("Form", "Label_52"))
        self.label_55.setText(_translate("Form", "Label_55"))
        self.label_53.setText(_translate("Form", "Labe_53"))
        self.label_57.setText(_translate("Form", "Label_57"))
        self.Label_22.setText(_translate("Form", "R3"))
        self.label_56.setText(_translate("Form", "Label_56"))
        self.Test1.setText(_translate("Form", "Test 1"))
        self.Test2.setText(_translate("Form", "Test 2"))
        self.Test3.setText(_translate("Form", "Test 3"))
        self.label_117.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.label_20.setText(_translate("Form", "TextLabel"))
        self.label_28.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "TextLabel"))
        self.label_30.setText(_translate("Form", "TextLabel"))
        self.label_38.setText(_translate("Form", "TextLabel"))
        self.label_39.setText(_translate("Form", "TextLabel"))
        self.label_41.setText(_translate("Form", "Label_41"))
        self.label_44.setText(_translate("Form", "Label_44"))
        self.label_42.setText(_translate("Form", "Label_42"))
        self.label_45.setText(_translate("Form", "Label_45"))
        self.label_46.setText(_translate("Form", "Label_46"))
        self.label_43.setText(_translate("Form", "Labe_43"))
        self.label_47.setText(_translate("Form", "Label_47"))
        self.Label_21.setText(_translate("Form", "R2"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_04.setText(_translate("Form", "Label_04"))
        self.label_05.setText(_translate("Form", "Label_05"))
        self.label_01.setText(_translate("Form", "Label_01"))
        self.label_03.setText(_translate("Form", "Labe_03"))
        self.label_07.setText(_translate("Form", "Label_07"))
        self.label_02.setText(_translate("Form", "Label_02"))
        self.label_06.setText(_translate("Form", "Label_06"))
        self.Label_08.setText(_translate("Form", "L1"))
        self.square_11.setText(_translate("Form", "square_11"))
        self.square_6.setText(_translate("Form", "square_6"))
        self.square_1.setText(_translate("Form", "square_1"))
        self.square_10.setText(_translate("Form", "square_10"))
        self.square_2.setText(_translate("Form", "square_2"))
        self.square_7.setText(_translate("Form", "square_7"))
        self.square_3.setText(_translate("Form", "square_3"))
        self.square_8.setText(_translate("Form", "square_8"))
        self.square_5.setText(_translate("Form", "square_5"))
        self.square_14.setText(_translate("Form", "square_14"))
        self.square_9.setText(_translate("Form", "square_9"))
        self.square_12.setText(_translate("Form", "square_12"))
        self.square_0.setText(_translate("Form", "square_0"))
        self.square_13.setText(_translate("Form", "square_013"))
        self.square_4.setText(_translate("Form", "square_4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

